server:
  port: 8080

spring:
  application:
    name: tender-platform
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: tms

management:
  endpoints:
    web:
      exposure:
        include: health,info

tender:
  seed:
    enabled: false
    data-location: classpath:db/seed/demo-data.json
    force: false
  documents:
    storage-dir: uploads
    max-size-bytes: 5242880
